dlab-11 add comment about credentials
ministryofjustice/data-platform-products pull request #11
Opened 2023-03-09 11:23 UTC by hemeshpatel-moj

2023-03-09 11:47 UTC, PriyaBasker23 approved these changes

2023-03-16 11:25 UTC, jacobwoffenden commented on .github/workflows/test.yaml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
```

2023-03-16 11:25 UTC, jacobwoffenden commented on .github/workflows/test.yaml
> +        uses: actions/setup-python@v1
```suggestion
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
```

2023-03-16 11:26 UTC, jacobwoffenden commented on .github/workflows/test.yaml
> +          pip install -r data-products/_example_2/requirements.txt
```suggestion
        run: |
          pip install -r data-products/_example_2/requirements.txt
```

2023-03-16 11:27 UTC, jacobwoffenden commented on .github/workflows/test.yaml
> +          fetch-depth: 1
Is this required?

2023-03-16 11:29 UTC, jacobwoffenden commented on .github/workflows/test.yaml
Can this be renamed to something more descriptive?

`data-product-example-2-test.yml`

2023-03-16 11:37 UTC, jacobwoffenden requested changes

2023-03-16 12:43 UTC, jacobwoffenden requested changes

2023-03-16 12:43 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-test.yaml
> +      - .github/workflows/<this workflow file>
```suggestion
      - .github/workflows/data-product-example-2-test.yaml
```

2023-03-16 12:43 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-test.yaml
> +          pytest tests/ -vv;
```suggestion
      - name: Install Python dependencies
        run: |
          pip install --requirement requirements.txt

      - name: Run tests with pytest
        run: |
          pytest tests/ -vv;
```

2023-03-16 13:26 UTC, jacobwoffenden approved these changes

2023-03-17 09:58 UTC, merged