Dplab 35 send data product
ministryofjustice/data-platform-products pull request #15
Opened 2023-03-28 15:44 UTC by murdo-moj

2023-03-28 16:31 UTC, murdo-moj commented on .github/workflows/zip-data-products.yml
> +  pull_request:
I think it should only trigger on pushes to main

2023-03-28 16:42 UTC, jacobwoffenden requested changes

2023-03-28 16:42 UTC, jacobwoffenden commented on .github/workflows/zip-data-products.yml
Are you able to refactor based on https://github.com/ministryofjustice/data-platform-products/blob/main/.github/workflows/data-product-example-2-test.yaml

Specifically:
- Changing the file name - `data-product-example-2-poc.yaml` ?
- Do you want to trigger this workflow on changes to `'data-products/**'`
- Can `working-directory` be set to `data-products/_example_2`
- Update actions to use SHA references instead of `@vX`

2023-03-28 17:05 UTC, hemeshpatel-moj commented
Am I correct in saying this workflow is likely to run in parallel with `data-product-example-2-test.yaml`, if yes. We should create a dependancy - if `data-product-example-2-test.yaml` pass then this `yml` is executed. To prevent broken/ untested data products from being published in the S3 bucket.

2023-03-28 21:09 UTC, PriyaBasker23 commented on .github/workflows/zip-data-products.yml
Agree Name - can be changed to data-product-example-2-poc.yaml

2023-03-28 21:30 UTC, PriyaBasker23 commented on .github/workflows/zip-data-products.yml
Add  needs: job Data Product - example_2 - Test

2023-03-28 21:31 UTC, PriyaBasker23 commented on .github/workflows/zip-data-products.yml
> +    name: Test
Name could be something descriptive rather than test

2023-03-28 21:34 UTC, PriyaBasker23 commented on .github/workflows/zip-data-products.yml
> +      - 'data-products/**'
data-products/_example_2/**

2023-03-29 09:03 UTC, hemeshpatel-moj commented on .github/workflows/data-product-example-2-poc.yaml
>          run: python package_data_product.py
If working directory is `data-products/_example_2`, then this needs to change as this is in the `data-products/` directory. You can either change it here by adding `../package_data_product.py` or changing where the `package_data_product.py` lives in the data_products repo

2023-03-29 09:04 UTC, murdo-moj commented on .github/workflows/data-product-example-2-poc.yaml
>          run: python package_data_product.py
I moved it because it's specific to _example_2

2023-04-03 08:46 UTC, jacobwoffenden requested changes

2023-04-03 08:46 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-poc.yaml
> +name: POC - zip and upload _example_2
```suggestion
name: Data Product - example_2 - PoC
```
as per https://github.com/ministryofjustice/data-platform-products/blob/main/.github/workflows/data-product-example-2-test.yaml#L2

2023-04-03 08:46 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-poc.yaml
> +      - ".github/workflows/data-product-example-2-poc.yaml"
```suggestion
    paths:
      - data-products/_example_2/**
      - .github/workflows/data-product-example-2-poc.yaml
```
These don't need wrapping

2023-04-03 08:46 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-poc.yaml
> +      contents: read # This is required for actions/checkout
```suggestion
```
I don't think this is explicitly required as this is a public repository, see https://github.com/ministryofjustice/data-platform-products/blob/main/.github/workflows/data-product-example-2-test.yaml

2023-04-03 08:46 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-poc.yaml
> +        python-version: [3.10.10]
Is this going be a matrix? as in, will more Python versions be added to this?

2023-04-03 08:46 UTC, jacobwoffenden commented on .github/workflows/data-product-example-2-poc.yaml
> +          fetch-depth: 2
Is this required?

2023-04-03 11:20 UTC, PriyaBasker23 commented on .github/workflows/data-product-example-2-poc.yaml
> +          fetch-depth: 2
fetch-depth: 1 -pulls the latest which is ok. We dont need to pull the entire history

2023-04-03 11:25 UTC, PriyaBasker23 commented on .github/workflows/data-product-example-2-poc.yaml
> +          fetch-depth: 2
# Number of commits to fetch. 0 indicates all history for all branches and tags.
    # Default: 1
    fetch-depth: ''.

2023-04-03 11:25 UTC, PriyaBasker23 commented on .github/workflows/data-product-example-2-poc.yaml
> +          fetch-depth: 2
So you dont need it

2023-04-03 11:31 UTC, PriyaBasker23 approved these changes

2023-04-03 11:50 UTC, jacobwoffenden approved these changes

2023-04-03 11:51 UTC, merged