Abstracted test data to csv
ministryofjustice/data-platform-products pull request #31
Opened 2023-05-30 15:25 UTC by murdo-moj

https://github.com/ministryofjustice/data-platform/issues/393

* Have formal test data files which are read in the tests
* Annotate the github PR with pytest failures to be more user friendly

2023-06-02 10:55 UTC, PriyaBasker23 submitted a review, later dismissed

2023-06-06 09:38 UTC, PriyaBasker23 approved these changes, later dismissed

2023-06-06 13:05 UTC, jacobwoffenden requested changes

2023-06-06 13:05 UTC, jacobwoffenden commented on .github/workflows/data-product-prison-example-test.yaml
> +        run: pip install pytest-github-actions-annotate-failures
Can this be put into another requirements file with a version? I'm going to be rolling out Dependabot for Pip soon, so would be good to get this under its robotic remit 🤖

2023-06-06 13:23 UTC, jacobwoffenden approved these changes

2023-06-06 13:55 UTC, bagg3rs approved these changes

2023-06-06 13:56 UTC, merged